__merge__: /src/api/comp_control_method.yaml
name: global_feature
label: Random integration
summary: Feature values are randomly permuted
description: Feature values are randomly permuted
namespace: batch_integration/control_methods/random_integration
info:
  preferred_normalization: log_cp10k
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
  - path: /src/control_methods/utils.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, lowmem, lowcpu]
